// frontend-react/src/App.jsx
import React, { useEffect, useState } from "react";

// This shell connects to backend/'s real API (/api/widgets) rather than
// carrying its own copy of the same JavaScript tool-trigger fixtures —
// backend/quality/ is the single source for JS tooling in this branch.
export default function App() {
  const [widgets, setWidgets] = useState([]);

  useEffect(() => {
    fetch("/api/widgets")
      .then((r) => r.json())
      .then((data) => setWidgets(data.widgets))
      .catch(() => setWidgets([]));
  }, []);

  return (
    <div>
      <h1>Micro-Frontend Shell (React)</h1>
      <ul>
        {widgets.map((w) => (
          <li key={w.id}>{w.label}</li>
        ))}
      </ul>
    </div>
  );
}

// frontend-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';

interface Widget {
  id: number;
  label: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, HttpClientModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {
  title = 'Micro-Frontend Remote (Angular)';
  widgets: Widget[] = [];

  constructor(private http: HttpClient) {}

  // Connects to backend/'s real API (/api/widgets) - same pattern as
  // frontend-react - rather than carrying its own copy of backend logic.
  ngOnInit(): void {
    this.http.get<{ widgets: Widget[] }>('/api/widgets').subscribe({
      next: (data) => (this.widgets = data.widgets),
      error: () => (this.widgets = []),
    });
  }
}

<h1>{{ title }}</h1>
<ul>
  <li *ngFor="let w of widgets">{{ w.label }}</li>
</ul>
